### PR TITLE
updates to tabs mixin

### PR DESCRIPTION
**Pull request by jgallen23**
Why is this pull request necessary:

- allow for custom parent class
- es6
- linting
- updated example to show how to style

Notify or mention any users: @chrisopedia

### CODE REVIEW

**Comment by jgallen23** [comment]
question: should we pass in colors to handle backgrounds and hover styles or leave that to the site?

**Comment by chrisopedia** [comment]
Do we handle colors on clientkit? I don't recall us dealing with colors in mixins. If that's the case I say leave it to the clients site

**Comment by jgallen23** [comment]
Yes. See colors.yaml

**Comment by chrisopedia** [comment]
Yeah. I guess we do have colors in the buttons.

**Comment by chrisopedia** [comment]
Maybe colors we need is just for a border color? Do we have any visuals for tabs we can base it off

**Comment by chrisopedia** [comment]
👍

**Pull request merged**
