### PR TITLE
Close

### PR DESCRIPTION
**Pull request by chrisopedia**
Why is this pull request necessary:
1. because greg said so, haha
2. provides a close class for modals or notifications or anything that would require a close button so its standardized

Changes proposed in this pull request:
- create a helper that provides a hover and focus state

Notify or mention any users:

@jgallen23

### CODE REVIEW

**Comment by jgallen23** [comment]
two things.  
1) can we add inline documentation and remove example?
2) can we set the content of it? or do I need to copy and paste the nice little x every time?

**Comment by chrisopedia** [comment]
1. done and pushed
2. I don't really have a good reason for or against except to say I've never seen anyone do that which makes me feel like having the text inside is required.

**Comment by jgallen23** [comment]
kill the example html

**Comment by chrisopedia** [comment]
done

**Pull request closed without merging**
